name: General
description: This is a template for reporting a general issue.
# If you want to enable automatic linking to projects,
# uncomment the following line and replace the project ID
# with the ID of your project.
# projects: ["pipepal"]
title: 'General: '
labels: [general]
body:
- type: textarea
  id: description
  attributes:
    label: Text
    description: Please, provide a clear and concise description of the issue.
    placeholder: Please, provide a clear and concise description of the issue.
  validations:
    required: false