name: Build and publish docs

permissions:
  contents: write

on:
  workflow_run:
    workflows: [Python Tests]
    types:
    - completed
    branches:
    - main

jobs:
  build-and-publish-docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest
        python-version: ["3.11", "3.10"]
        deploy: [true]
    steps:
    - uses: actions/checkout@v4
      with:  # no need for the history
        fetch-depth: 1
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    # Cache Poetry dependencies to speed up builds
    - name: Cache Poetry virtualenv
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install --with docs
      shell: bash
    - name: Build docs
      run: |
        APP_MODULE_NAME=$(ls src -U | head -1)  # Get the first module name in the src directory
        poetry run pdoc src/"$APP_MODULE_NAME" -o docs_build -t docs/pdoc-theme --docformat google
        touch docs_build/.nojekyll
      shell: bash
    - name: Publish Docs
      if: ${{ matrix.deploy }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs_build