name: Auto-release on PR merge

on:
  # ATM, this is the closest trigger to a PR merging
  workflow_run:
    workflows: ["Python Tests"]
    branches: [main]
    types: [completed]

env:
  AUTO_VERSION: v11.1.1

jobs:
  check_tests_status:
    runs-on: ubuntu-latest
    steps:
      - name: Check outcome of previous workflow
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
            echo "Previous workflow was not successful. Conclusion: ${{ github.event.workflow_run.conclusion }}"
            exit 1
          fi

  auto-release:
    if: ${{ github.event.workflow_run.head_branch == 'main' }}
    needs: check_tests_status
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Prepare repository
        # Fetch full git history and tags
        run: git fetch --unshallow --tags

      - name: Unset header
        # checkout@v2 adds a header that makes branch protection report errors
        # because the Github action bot is not a collaborator on the repo
        run: git config --local --unset http.https://github.com/.extraheader

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Download auto
        run: |
          auto_download_url="$(curl -fsSL https://api.github.com/repos/intuit/auto/releases/tags/$AUTO_VERSION | jq -r '.assets[] | select(.name == "auto-linux.gz") | .browser_download_url')"
          wget -O- "$auto_download_url" | gunzip > ~/auto
          chmod a+x ~/auto

      - name: Create release
        run: |
          ~/auto shipit -vv
        env:
          GH_TOKEN: ${{ secrets.AUTO_ORG_TOKEN }}

